services:
  - type: web
    name: activemq
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ACTIVEMQ_ADMIN_LOGIN
        value: admin
      - key: ACTIVEMQ_ADMIN_PASSWORD
        value: admin
    ports:
      - port: 8161 # Web console
        protocol: http
      - port: 61616 # TCP for JMS
        protocol: tcp
